files:
  - source: MMOCore-Dist/src/main/resources/default/gui/*.yml
    translation: /**/MMOCore-Dist/src/main/resources/default/translation/%language%/gui/%file_name%.%file_extension%
  - source: MMOCore-Dist/src/main/resources/default/messages.yml
    translation: /**/MMOCore-Dist/src/main/resources/default/translation/%language%/%file_name%.%file_extension%
